security:
  oauth2:
    client:
      clientId: 334852530606209
      clientSecret: 47395165005897ed368c821c0a0fca6c
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
spring.main.allow-bean-definition-overriding: true